/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as VerificationRouteImport } from './routes/verification'
import { Route as TrackingRouteImport } from './routes/tracking'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomeRouteImport } from './routes/home'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CargoTrackingRouteImport } from './routes/cargo-tracking'
import { Route as CargoRouteImport } from './routes/cargo'
import { Route as AnnouncementsRouteImport } from './routes/announcements'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as RoleAvatarRouteImport } from './routes/RoleAvatar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TrackingReservationIdRouteImport } from './routes/tracking.$reservationId'
import { Route as PaymentGpIdRouteImport } from './routes/payment.$gpId'
import { Route as GpIdRouteImport } from './routes/gp.$id'
import { Route as ConfirmationReservationIdRouteImport } from './routes/confirmation.$reservationId'
import { Route as BookingGpIdRouteImport } from './routes/booking.$gpId'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTransactionsRouteImport } from './routes/admin.transactions'
import { Route as AdminGpRouteImport } from './routes/admin.gp'
import { Route as AdminCargoRouteImport } from './routes/admin.cargo'
import { Route as AdminAnnouncementsRouteImport } from './routes/admin.announcements'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const VerificationRoute = VerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackingRoute = TrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CargoTrackingRoute = CargoTrackingRouteImport.update({
  id: '/cargo-tracking',
  path: '/cargo-tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const CargoRoute = CargoRouteImport.update({
  id: '/cargo',
  path: '/cargo',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsRoute = AnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const RoleAvatarRoute = RoleAvatarRouteImport.update({
  id: '/RoleAvatar',
  path: '/RoleAvatar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TrackingReservationIdRoute = TrackingReservationIdRouteImport.update({
  id: '/$reservationId',
  path: '/$reservationId',
  getParentRoute: () => TrackingRoute,
} as any)
const PaymentGpIdRoute = PaymentGpIdRouteImport.update({
  id: '/payment/$gpId',
  path: '/payment/$gpId',
  getParentRoute: () => rootRouteImport,
} as any)
const GpIdRoute = GpIdRouteImport.update({
  id: '/gp/$id',
  path: '/gp/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmationReservationIdRoute =
  ConfirmationReservationIdRouteImport.update({
    id: '/confirmation/$reservationId',
    path: '/confirmation/$reservationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const BookingGpIdRoute = BookingGpIdRouteImport.update({
  id: '/booking/$gpId',
  path: '/booking/$gpId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTransactionsRoute = AdminTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGpRoute = AdminGpRouteImport.update({
  id: '/gp',
  path: '/gp',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCargoRoute = AdminCargoRouteImport.update({
  id: '/cargo',
  path: '/cargo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnnouncementsRoute = AdminAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/RoleAvatar': typeof RoleAvatarRoute
  '/admin': typeof AdminRouteWithChildren
  '/announcements': typeof AnnouncementsRoute
  '/cargo': typeof CargoRoute
  '/cargo-tracking': typeof CargoTrackingRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/scan': typeof ScanRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/tracking': typeof TrackingRouteWithChildren
  '/verification': typeof VerificationRoute
  '/wallet': typeof WalletRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/cargo': typeof AdminCargoRoute
  '/admin/gp': typeof AdminGpRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/booking/$gpId': typeof BookingGpIdRoute
  '/confirmation/$reservationId': typeof ConfirmationReservationIdRoute
  '/gp/$id': typeof GpIdRoute
  '/payment/$gpId': typeof PaymentGpIdRoute
  '/tracking/$reservationId': typeof TrackingReservationIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/RoleAvatar': typeof RoleAvatarRoute
  '/announcements': typeof AnnouncementsRoute
  '/cargo': typeof CargoRoute
  '/cargo-tracking': typeof CargoTrackingRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/scan': typeof ScanRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/tracking': typeof TrackingRouteWithChildren
  '/verification': typeof VerificationRoute
  '/wallet': typeof WalletRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/cargo': typeof AdminCargoRoute
  '/admin/gp': typeof AdminGpRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/booking/$gpId': typeof BookingGpIdRoute
  '/confirmation/$reservationId': typeof ConfirmationReservationIdRoute
  '/gp/$id': typeof GpIdRoute
  '/payment/$gpId': typeof PaymentGpIdRoute
  '/tracking/$reservationId': typeof TrackingReservationIdRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/RoleAvatar': typeof RoleAvatarRoute
  '/admin': typeof AdminRouteWithChildren
  '/announcements': typeof AnnouncementsRoute
  '/cargo': typeof CargoRoute
  '/cargo-tracking': typeof CargoTrackingRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/scan': typeof ScanRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/tracking': typeof TrackingRouteWithChildren
  '/verification': typeof VerificationRoute
  '/wallet': typeof WalletRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/cargo': typeof AdminCargoRoute
  '/admin/gp': typeof AdminGpRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/booking/$gpId': typeof BookingGpIdRoute
  '/confirmation/$reservationId': typeof ConfirmationReservationIdRoute
  '/gp/$id': typeof GpIdRoute
  '/payment/$gpId': typeof PaymentGpIdRoute
  '/tracking/$reservationId': typeof TrackingReservationIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/RoleAvatar'
    | '/admin'
    | '/announcements'
    | '/cargo'
    | '/cargo-tracking'
    | '/dashboard'
    | '/forgot-password'
    | '/home'
    | '/login'
    | '/notifications'
    | '/profile'
    | '/reset-password'
    | '/scan'
    | '/search'
    | '/signup'
    | '/tracking'
    | '/verification'
    | '/wallet'
    | '/admin/announcements'
    | '/admin/cargo'
    | '/admin/gp'
    | '/admin/transactions'
    | '/admin/users'
    | '/booking/$gpId'
    | '/confirmation/$reservationId'
    | '/gp/$id'
    | '/payment/$gpId'
    | '/tracking/$reservationId'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/RoleAvatar'
    | '/announcements'
    | '/cargo'
    | '/cargo-tracking'
    | '/dashboard'
    | '/forgot-password'
    | '/home'
    | '/login'
    | '/notifications'
    | '/profile'
    | '/reset-password'
    | '/scan'
    | '/search'
    | '/signup'
    | '/tracking'
    | '/verification'
    | '/wallet'
    | '/admin/announcements'
    | '/admin/cargo'
    | '/admin/gp'
    | '/admin/transactions'
    | '/admin/users'
    | '/booking/$gpId'
    | '/confirmation/$reservationId'
    | '/gp/$id'
    | '/payment/$gpId'
    | '/tracking/$reservationId'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/RoleAvatar'
    | '/admin'
    | '/announcements'
    | '/cargo'
    | '/cargo-tracking'
    | '/dashboard'
    | '/forgot-password'
    | '/home'
    | '/login'
    | '/notifications'
    | '/profile'
    | '/reset-password'
    | '/scan'
    | '/search'
    | '/signup'
    | '/tracking'
    | '/verification'
    | '/wallet'
    | '/admin/announcements'
    | '/admin/cargo'
    | '/admin/gp'
    | '/admin/transactions'
    | '/admin/users'
    | '/booking/$gpId'
    | '/confirmation/$reservationId'
    | '/gp/$id'
    | '/payment/$gpId'
    | '/tracking/$reservationId'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RoleAvatarRoute: typeof RoleAvatarRoute
  AdminRoute: typeof AdminRouteWithChildren
  AnnouncementsRoute: typeof AnnouncementsRoute
  CargoRoute: typeof CargoRoute
  CargoTrackingRoute: typeof CargoTrackingRoute
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ScanRoute: typeof ScanRoute
  SearchRoute: typeof SearchRoute
  SignupRoute: typeof SignupRoute
  TrackingRoute: typeof TrackingRouteWithChildren
  VerificationRoute: typeof VerificationRoute
  WalletRoute: typeof WalletRoute
  BookingGpIdRoute: typeof BookingGpIdRoute
  ConfirmationReservationIdRoute: typeof ConfirmationReservationIdRoute
  GpIdRoute: typeof GpIdRoute
  PaymentGpIdRoute: typeof PaymentGpIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verification': {
      id: '/verification'
      path: '/verification'
      fullPath: '/verification'
      preLoaderRoute: typeof VerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracking': {
      id: '/tracking'
      path: '/tracking'
      fullPath: '/tracking'
      preLoaderRoute: typeof TrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cargo-tracking': {
      id: '/cargo-tracking'
      path: '/cargo-tracking'
      fullPath: '/cargo-tracking'
      preLoaderRoute: typeof CargoTrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cargo': {
      id: '/cargo'
      path: '/cargo'
      fullPath: '/cargo'
      preLoaderRoute: typeof CargoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements': {
      id: '/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/RoleAvatar': {
      id: '/RoleAvatar'
      path: '/RoleAvatar'
      fullPath: '/RoleAvatar'
      preLoaderRoute: typeof RoleAvatarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/tracking/$reservationId': {
      id: '/tracking/$reservationId'
      path: '/$reservationId'
      fullPath: '/tracking/$reservationId'
      preLoaderRoute: typeof TrackingReservationIdRouteImport
      parentRoute: typeof TrackingRoute
    }
    '/payment/$gpId': {
      id: '/payment/$gpId'
      path: '/payment/$gpId'
      fullPath: '/payment/$gpId'
      preLoaderRoute: typeof PaymentGpIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gp/$id': {
      id: '/gp/$id'
      path: '/gp/$id'
      fullPath: '/gp/$id'
      preLoaderRoute: typeof GpIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmation/$reservationId': {
      id: '/confirmation/$reservationId'
      path: '/confirmation/$reservationId'
      fullPath: '/confirmation/$reservationId'
      preLoaderRoute: typeof ConfirmationReservationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/$gpId': {
      id: '/booking/$gpId'
      path: '/booking/$gpId'
      fullPath: '/booking/$gpId'
      preLoaderRoute: typeof BookingGpIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/transactions': {
      id: '/admin/transactions'
      path: '/transactions'
      fullPath: '/admin/transactions'
      preLoaderRoute: typeof AdminTransactionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/gp': {
      id: '/admin/gp'
      path: '/gp'
      fullPath: '/admin/gp'
      preLoaderRoute: typeof AdminGpRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cargo': {
      id: '/admin/cargo'
      path: '/cargo'
      fullPath: '/admin/cargo'
      preLoaderRoute: typeof AdminCargoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/announcements': {
      id: '/admin/announcements'
      path: '/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AdminAnnouncementsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnnouncementsRoute: typeof AdminAnnouncementsRoute
  AdminCargoRoute: typeof AdminCargoRoute
  AdminGpRoute: typeof AdminGpRoute
  AdminTransactionsRoute: typeof AdminTransactionsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnnouncementsRoute: AdminAnnouncementsRoute,
  AdminCargoRoute: AdminCargoRoute,
  AdminGpRoute: AdminGpRoute,
  AdminTransactionsRoute: AdminTransactionsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface TrackingRouteChildren {
  TrackingReservationIdRoute: typeof TrackingReservationIdRoute
}

const TrackingRouteChildren: TrackingRouteChildren = {
  TrackingReservationIdRoute: TrackingReservationIdRoute,
}

const TrackingRouteWithChildren = TrackingRoute._addFileChildren(
  TrackingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RoleAvatarRoute: RoleAvatarRoute,
  AdminRoute: AdminRouteWithChildren,
  AnnouncementsRoute: AnnouncementsRoute,
  CargoRoute: CargoRoute,
  CargoTrackingRoute: CargoTrackingRoute,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ScanRoute: ScanRoute,
  SearchRoute: SearchRoute,
  SignupRoute: SignupRoute,
  TrackingRoute: TrackingRouteWithChildren,
  VerificationRoute: VerificationRoute,
  WalletRoute: WalletRoute,
  BookingGpIdRoute: BookingGpIdRoute,
  ConfirmationReservationIdRoute: ConfirmationReservationIdRoute,
  GpIdRoute: GpIdRoute,
  PaymentGpIdRoute: PaymentGpIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
